name: movemedriver
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+29

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pusher:
    git:
      url: https://vagners2@bitbucket.org/343mobile/pusherflutter.git
      path: ''

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  json_annotation: ^4.6.0
  image_picker: ^0.8.6+1

  #externals libs
  shared_preferences: ^2.0.17
  flutter_masked_text: ^0.8.0
  intl: ^0.17.0
  tuple: ^2.0.1
  #flutter_facebook_login: ^3.0.0
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  android_intent: ^2.0.2
  device_info: ^2.0.3
  package_info: ^2.0.2
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^12.0.4
  sliding_up_panel: ^2.0.0+1
  uuid: ^4.1.0
  screen: ^0.0.5
  provider: ^6.1.1
  get_it: ^7.6.0
  event_bus: ^2.0.0
  flushbar: ^1.10.4
  url_launcher: ^6.1.8
  flutter_svg: ^0.23.0+1
  photo_view: ^0.14.0
  flutter_ringtone_player: ^3.2.0
  image_crop: ^0.4.0
  map_launcher: ^3.1.0
  qr_flutter: ^4.0.0
  flutter_html: ^2.2.1
  file_picker: ^4.6.1
  date_range_picker: ^1.0.6
  facebook_app_events: ^0.19.0
  geolocator: ^10.1.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/icons/
    - assets/gifs/

  fonts:
    #    - family: MaterialIcons
    #      fonts:
    #        - asset: assets/fonts/MaterialIcons-Regular.ttf
    - family: MoveMeIcons
      fonts:
        - asset: assets/fonts/MoveMeIcons.ttf
    - family: Montserrat
      fonts:
        #- asset: assets/fonts/Branding-Black.otf
        #- asset: assets/fonts/Branding-BlackItalic.otf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal